### ISSUE TITLE
Error with pip-tools due to setupmeta being installed

### ISSUE THREAD

**Issue by blueyed** [zsimic/setupmeta#22]
I am seeing an error when using pip-tools from an environment where setupmeta is installed also.

setupmeta's `distutils_hook` hook is called there.

setupmeta get/writes the following in `parse_requirements`
(https://github.com/zsimic/setupmeta/blob/bae0550b4aafabffbf7557382c56abf914ea4830/setupmeta/model.py#L346-L347):

```
[
  'sqlalchemy',
  '[:python_version < "3.7"]',
  'aiocontextvars',
  '[mysql]',
  'aiomysql',
  'pymysql',
  '[postgresql]',
  'asyncpg',
  'psycopg2-binary',
  '[sqlite]',
  'aiosqlite'
]
```

```
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
  File "…/Vcs/pip-tools/.venv/lib/python3.7/site-packages/pip/_vendor/packaging/requirements.py", line 93, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "…/Vcs/pip-tools/.venv/lib/python3.7/site-packages/pip/_vendor/pyparsing.py", line 1828, in parseString
    raise exc
  File "…/Vcs/pip-tools/.venv/lib/python3.7/site-packages/pip/_vendor/pyparsing.py", line 1818, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "…/Vcs/pip-tools/.venv/lib/python3.7/site-packages/pip/_vendor/pyparsing.py", line 1562, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "…/Vcs/pip-tools/.venv/lib/python3.7/site-packages/pip/_vendor/pyparsing.py", line 3752, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "…/Vcs/pip-tools/.venv/lib/python3.7/site-packages/pip/_vendor/pyparsing.py", line 1566, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "…/Vcs/pip-tools/.venv/lib/python3.7/site-packages/pip/_vendor/pyparsing.py", line 3536, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected stringEnd (at char 11), (line:1, col:12)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/tmpw_lqp4v4build/databases/setup.py", line 66, in <module>
    "Programming Language :: Python :: 3.7",
  File "…/Vcs/pip-tools/.venv/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 134, in setup
    ok = dist.parse_command_line()
  File "…/Vcs/pip-tools/.venv/lib/python3.7/site-packages/setupmeta/hook.py", line 24, in distutils_hook
    dist._setupmeta = SetupMeta(dist)
  File "…/Vcs/pip-tools/.venv/lib/python3.7/site-packages/setupmeta/model.py", line 673, in __init__
    self.requirements = Requirements(self.pkg_info)
  File "…/Vcs/pip-tools/.venv/lib/python3.7/site-packages/setupmeta/model.py", line 561, in __init__
    self.install = self.get_requirements(True, pkg_info.requires_txt, "requirements.txt", "pinned.txt")
  File "…/Vcs/pip-tools/.venv/lib/python3.7/site-packages/setupmeta/model.py", line 596, in get_requirements
    return RequirementsEntry(path, abstract=abstract)
  File "…/Vcs/pip-tools/.venv/lib/python3.7/site-packages/setupmeta/model.py", line 547, in __init__
    reqs, links = parse_requirements(self.reqs)
  File "…/Vcs/pip-tools/.venv/lib/python3.7/site-packages/setupmeta/model.py", line 350, in parse_requirements
    for ir in pip_parse_requirements(temp, session=session):
  File "…/Vcs/pip-tools/.venv/lib/python3.7/site-packages/pip/_internal/req/req_file.py", line 112, in parse_requirements
    for req in req_iter:
  File "…/Vcs/pip-tools/.venv/lib/python3.7/site-packages/pip/_internal/req/req_file.py", line 193, in process_line
    isolated=isolated, options=req_options, wheel_cache=wheel_cache
  File "…/Vcs/pip-tools/.venv/lib/python3.7/site-packages/pip/_internal/req/constructors.py", line 280, in install_req_from_line
    extras = Requirement("placeholder" + extras_as_string.lower()).extras
  File "…/Vcs/pip-tools/.venv/lib/python3.7/site-packages/pip/_vendor/packaging/requirements.py", line 97, in __init__
    requirement_string[e.loc : e.loc + 8], e.msg
pip._vendor.packaging.requirements.InvalidRequirement: Parse error at "'[:python'": Expected stringEnd
----------------------------------------
Traceback (most recent call last):
  File "…/Vcs/pip-tools/.venv/bin/pip-compile", line 11, in <module>
    load_entry_point('pip-tools', 'console_scripts', 'pip-compile')()
  File "…/Vcs/pip-tools/.venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "…/Vcs/pip-tools/.venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "…/Vcs/pip-tools/.venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "…/Vcs/pip-tools/.venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "…/Vcs/pip-tools/.venv/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "…/Vcs/pip-tools/piptools/scripts/compile.py", line 352, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "…/Vcs/pip-tools/piptools/resolver.py", line 119, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "…/Vcs/pip-tools/piptools/resolver.py", line 225, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "…/Vcs/pip-tools/piptools/resolver.py", line 331, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "…/Vcs/pip-tools/piptools/repositories/local.py", line 66, in get_dependencies
    return self.repository.get_dependencies(ireq)
  File "…/Vcs/pip-tools/piptools/repositories/pypi.py", line 255, in get_dependencies
    download_dir, ireq, wheel_cache
  File "…/Vcs/pip-tools/piptools/repositories/pypi.py", line 218, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "…/Vcs/pip-tools/.venv/lib/python3.7/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "…/Vcs/pip-tools/.venv/lib/python3.7/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "…/Vcs/pip-tools/.venv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 368, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "…/Vcs/pip-tools/.venv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 177, in prep_for_dist
    self.req.prepare_metadata()
  File "…/Vcs/pip-tools/.venv/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 539, in prepare_metadata
    self.run_egg_info()
  File "…/Vcs/pip-tools/.venv/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 617, in run_egg_info
    command_desc='python setup.py egg_info')
  File "…/Vcs/pip-tools/.venv/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 776, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmpw_lqp4v4build/databases/
```

Trace with SETUPMETA_DEBUG - added `requirements line` there:

```
Complete output from command python setup.py egg_info:
:: setup.py found from call stack: /tmp/tmp9f4z8zeybuild/databases/setup.py
:: project dir: /tmp/tmp9f4z8zeybuild/databases
:: [-> explicit] author=Tom Christie
:: [-> explicit] author_email=tom@tomchristie.com
:: [-> explicit] classifiers=9 items: ["Development Status :: 3 - Alpha", "Environment :: Web Environment", "Intended Audience :: Developers", "License :: OSI Approved :: BSD License", "...
:: [-> explicit] description=Async database support for Python.
:: [-> explicit] license=BSD
:: [-> explicit] long_description=# Databases <p> <a href="https://travis-ci.org/encode/databases"> <img src="https://travis-ci.org/encode/databases.svg?branch=master" alt="Build Status"> </a...
:: [-> explicit] long_description_content_type=text/markdown
:: [-> explicit] name=databases
:: [-> explicit] url=https://github.com/encode/databases
:: [-> explicit] version=0.2.2
:: [-> explicit] extras_require={:python_version < "3.7": ["aiocontextvars"], mysql: ["aiomysql", "pymysql"], postgresql: ["asyncpg", "psycopg2-binary"], sqlite: ["aiosqlite"]}
:: [-> explicit] install_requires=["sqlalchemy"]
:: [-> explicit] package_data={databases: ["py.typed"]}
:: [-> explicit] packages=["databases", "databases/backends"]
:: [-> explicit] python_requires=>=3.6
:: [-> PKG-INFO] name=databases
:: [-> PKG-INFO] version=0.2.2
:: [-> PKG-INFO] description=Async database support for Python.
:: [-> PKG-INFO] url=https://github.com/encode/databases
:: [-> PKG-INFO] author=Tom Christie
:: [-> PKG-INFO] author_email=tom@tomchristie.com
:: [-> PKG-INFO] license=BSD
:: [-> PKG-INFO] long_description=# Databases <p> <a href="https://travis-ci.org/encode/databases"> <img src="https://travis-ci.org/encode/databases.svg?branch=master" alt="Build Status"> </a...
:: [-> PKG-INFO] classifiers=9 items: ["Development Status :: 3 - Alpha", "Environment :: Web Environment", "Intended Audience :: Developers", "License :: OSI Approved :: BSD License", "...
:: [-> PKG-INFO] long_description_content_type=text/markdown
:: [-> databases/__init__.py:3] version=0.2.2
:: could not determine SCM for '/tmp/tmp9f4z8zeybuild/databases'
:: versioning given: 'None', strategy: [None], problem: [setupmeta versioning not enabled]
:: not auto-filling version, versioning is disabled
:: [<- auto-fill] bugtrack_url=https://github.com/encode/databases/issues
:: found requirements: /tmp/tmp9f4z8zeybuild/databases/databases.egg-info/requires.txt
:: requirements line: sqlalchemy
:: requirements line: [:python_version < "3.7"]
:: requirements line: aiocontextvars
:: requirements line: [mysql]
:: requirements line: aiomysql
:: requirements line: pymysql
:: requirements line: [postgresql]
:: requirements line: asyncpg
:: requirements line: psycopg2-binary
:: requirements line: [sqlite]
:: requirements line: aiosqlite
Traceback (most recent call last):
```

1. So it seems like something is creating an invalid requirements file there?
   Maybe pip-tools?

2. setupmeta should probably not do anything here - when pip-tools is
   compiling/pinning other packages, which are not using setupmeta themselves?!

TEST CASE:

1. create a temporary virtualenv, I was using Python 3.7
2. `pip install setupmeta pip-tools`
3. `echo databases | pip-compile - -o -`

**Comment by blueyed** [comment]
I guess the `requires.txt` is not really invalid, is it? - but just not handled correctly?

It comes via `/tmp/tmp50r3596dbuild/databases/databases.egg-info/requires.txt`:
```
sqlalchemy

[:python_version < "3.7"]
aiocontextvars

[mysql]
aiomysql
pymysql

[postgresql]
asyncpg
psycopg2-binary

[sqlite]
aiosqlite
```

**Comment by zsimic** [comment]
Interesting, never thought of using it this way :)

Why do you `pip install setupmeta`? Usually it's a `setup_requires` (in order to just allow you to have a lighter `setup.py`). Is the intent here to inject setupmeta somehow into [databases](https://pypi.org/project/databases/)?

I'm not sure even how setupmeta comes into play here, I'll take a look out of curiosity :)

What `parse_requirements()` is trying to do is ask pip to distinguish links from actual deps. Ie differentiate something like `mysql` in requirements vs something like `-e some-git-repo/foo/...#some-egg`
And the purpose of that is to try and auto-fill `install_requires` and `tests_require`.

I do wonder how setupmeta ends up getting injected into the `databases` installation there, I thought the `setup_require=["setupmeta"]` entry in `setup.py` was what hooked it into setuptools (wouldn't think a `pip install setupmeta` would end up also having its hooks registered like that)

**Comment by blueyed** [comment]
> Why do you `pip install setupmeta`?

Just out of habit I guess.. :)

To be clear: I've noticed this when using pip-compile from pip-tools for a project, where setupmeta is installed (although it does not need to be).

So it gets hooked into it just because it is installed probably.

It works in my project also when uninstalling it (but setuptools still uses it via `setup_requires`).

**Comment by zsimic** [comment]
I'll add a test case to cover this, at the very least setupmeta should not fail (on anything), and should simply say "can't auto-fill requirements, or something of the sort if the pip call borks).

Looking at databases' `setup.py`, there's nothing to auto-fill anyway :)

Wonder if I could also somehow detect that the intent is to let setupmeta auto-fill stuff, perhaps look for an explicit `setup_requires=["setupmeta"]`, and disable itself if not present (as to avoid that side loading taking place here)

**Comment by zsimic** [comment]
https://github.com/zsimic/setupmeta/pull/23

**Comment by blueyed** [comment]
Thank you, that works!
