### ISSUE TITLE
"Invalid requirement: '[:platform_system'" with PEP 508 classifiers

### ISSUE THREAD

**Issue by blueyed** [zsimic/setupmeta#26]
I am seeing a similar issue as reported in https://github.com/zsimic/setupmeta/issues/22 recently, when using a `setup.py` as follows - triggered by `"pyreadline;platform_system=='Windows'"`:

```python
from setuptools import setup

setup(
    name='fancycompleter-pdbpp',
    setup_requires="setupmeta",
    install_requires=[
        "pyrepl",
        "pyreadline;platform_system=='Windows'",
    ]
)
```

```
GLOB sdist-make: …/Vcs/fancycompleter-git/setup.py
py37 recreate: /tmp/tox…/Vcs/fancycompleter-git/py37
py37 installdeps: pytest
py37 inst: /tmp/tox…/Vcs/fancycompleter-git/.tmp/package/1/fancycompleter-pdbpp-0.0.0.zip
ERROR: invocation failed (exit code 1), logfile: /tmp/tox…/Vcs/fancycompleter-git/py37/log/py37-2.log
================================================================================= log start ==================================================================================
Looking in indexes: http://localhost:3141/root/pypi/+simple/
Processing /tmp/tox…/Vcs/fancycompleter-git/.tmp/package/1/fancycompleter-pdbpp-0.0.0.zip
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "/tmp/tox…/Vcs/fancycompleter-git/py37/lib/python3.7/site-packages/pip/_vendor/packaging/requirements.py", line 93, in __init__
        req = REQUIREMENT.parseString(requirement_string)
      File "/tmp/tox…/Vcs/fancycompleter-git/py37/lib/python3.7/site-packages/pip/_vendor/pyparsing.py", line 1828, in parseString
        raise exc
      File "/tmp/tox…/Vcs/fancycompleter-git/py37/lib/python3.7/site-packages/pip/_vendor/pyparsing.py", line 1818, in parseString
        loc, tokens = self._parse( instring, 0 )
      File "/tmp/tox…/Vcs/fancycompleter-git/py37/lib/python3.7/site-packages/pip/_vendor/pyparsing.py", line 1562, in _parseNoCache
        loc,tokens = self.parseImpl( instring, preloc, doActions )
      File "/tmp/tox…/Vcs/fancycompleter-git/py37/lib/python3.7/site-packages/pip/_vendor/pyparsing.py", line 3752, in parseImpl
        loc, exprtokens = e._parse( instring, loc, doActions )
      File "/tmp/tox…/Vcs/fancycompleter-git/py37/lib/python3.7/site-packages/pip/_vendor/pyparsing.py", line 1562, in _parseNoCache
        loc,tokens = self.parseImpl( instring, preloc, doActions )
      File "/tmp/tox…/Vcs/fancycompleter-git/py37/lib/python3.7/site-packages/pip/_vendor/pyparsing.py", line 4098, in parseImpl
        return self.expr._parse( instring, loc, doActions, callPreParse=False )
      File "/tmp/tox…/Vcs/fancycompleter-git/py37/lib/python3.7/site-packages/pip/_vendor/pyparsing.py", line 1562, in _parseNoCache
        loc,tokens = self.parseImpl( instring, preloc, doActions )
      File "/tmp/tox…/Vcs/fancycompleter-git/py37/lib/python3.7/site-packages/pip/_vendor/pyparsing.py", line 3735, in parseImpl
        loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
      File "/tmp/tox…/Vcs/fancycompleter-git/py37/lib/python3.7/site-packages/pip/_vendor/pyparsing.py", line 1566, in _parseNoCache
        loc,tokens = self.parseImpl( instring, preloc, doActions )
      File "/tmp/tox…/Vcs/fancycompleter-git/py37/lib/python3.7/site-packages/pip/_vendor/pyparsing.py", line 2935, in parseImpl
        raise ParseException(instring, loc, self.errmsg, self)
    pip._vendor.pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/tmp/tox…/Vcs/fancycompleter-git/py37/lib/python3.7/site-packages/pip/_internal/req/constructors.py", line 285, in install_req_from_line
        req = Requirement(req_as_string)
      File "/tmp/tox…/Vcs/fancycompleter-git/py37/lib/python3.7/site-packages/pip/_vendor/packaging/requirements.py", line 97, in __init__
        requirement_string[e.loc : e.loc + 8], e.msg
    pip._vendor.packaging.requirements.InvalidRequirement: Parse error at "'[:platfo'": Expected W:(abcd...)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-76dfx9ft/setup.py", line 8, in <module>
        "pyreadline;platform_system=='Windows'",
      File "/tmp/tox…/Vcs/fancycompleter-git/py37/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.7/distutils/core.py", line 134, in setup
        ok = dist.parse_command_line()
      File "/tmp/pip-req-build-76dfx9ft/.eggs/setupmeta-2.6.0-py3.7.egg/setupmeta/hook.py", line 23, in distutils_hook
        dist._setupmeta = SetupMeta(dist)
      File "/tmp/pip-req-build-76dfx9ft/.eggs/setupmeta-2.6.0-py3.7.egg/setupmeta/model.py", line 673, in __init__
        self.requirements = Requirements(self.pkg_info)
      File "/tmp/pip-req-build-76dfx9ft/.eggs/setupmeta-2.6.0-py3.7.egg/setupmeta/model.py", line 561, in __init__
        self.install = self.get_requirements(True, pkg_info.requires_txt, "requirements.txt", "pinned.txt")
      File "/tmp/pip-req-build-76dfx9ft/.eggs/setupmeta-2.6.0-py3.7.egg/setupmeta/model.py", line 596, in get_requirements
        return RequirementsEntry(path, abstract=abstract)
      File "/tmp/pip-req-build-76dfx9ft/.eggs/setupmeta-2.6.0-py3.7.egg/setupmeta/model.py", line 547, in __init__
        reqs, links = parse_requirements(self.reqs)
      File "/tmp/pip-req-build-76dfx9ft/.eggs/setupmeta-2.6.0-py3.7.egg/setupmeta/model.py", line 350, in parse_requirements
        for ir in pip_parse_requirements(temp, session=session):
      File "/tmp/tox…/Vcs/fancycompleter-git/py37/lib/python3.7/site-packages/pip/_internal/req/req_file.py", line 112, in parse_requirements
        for req in req_iter:
      File "/tmp/tox…/Vcs/fancycompleter-git/py37/lib/python3.7/site-packages/pip/_internal/req/req_file.py", line 193, in process_line
        isolated=isolated, options=req_options, wheel_cache=wheel_cache
      File "/tmp/tox…/Vcs/fancycompleter-git/py37/lib/python3.7/site-packages/pip/_internal/req/constructors.py", line 296, in install_req_from_line
        "Invalid requirement: '%s'\n%s" % (req_as_string, add_msg)
    pip._internal.exceptions.InstallationError: Invalid requirement: '[:platform_system'

    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-76dfx9ft/

================================================================================== log end ===================================================================================
__________________________________________________________________________________ summary ___________________________________________________________________________________
ERROR:   py37: InvocationError for command /tmp/tox…/Vcs/fancycompleter-git/py37/bin/python -m pip install --exists-action w /tmp/tox…/Vcs/fancycompleter-git/.tmp/package/1/fancycompleter-pdbpp-0.0.0.zip (exited with code 1)
```

**Comment by zsimic** [comment]
Just release setupmeta 2.6.1, which should fix this.

It was failing on unparseable reqs, now it will simply not auto-fill anything is pip can't parse reqs file.

**Comment by blueyed** [comment]
Awesome, thanks!

That fixes it.

btw: `explain` looked correctly before already:
```
extras_require: (explicit) {:platform_system == "Windows": ["pyreadline"]}
install_requires: (explicit) ["pyrepl"]
```
