### ISSUE TITLE
UnicodeDecodeError in load_contents with Python 2.7

### ISSUE THREAD

**Issue by blueyed** [zsimic/setupmeta#45]
```
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting fancycompleter
  Downloading fancycompleter-0.9.0.tar.gz (10 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zu5MqZ/fancycompleter/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zu5MqZ/fancycompleter/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-zu5MqZ/fancycompleter/pip-egg-info
         cwd: /tmp/pip-install-zu5MqZ/fancycompleter/
    Complete output (20 lines):
    DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-zu5MqZ/fancycompleter/setup.py", line 32, in <module>
        "pyreadline;platform_system=='Windows'",
      File "/usr/local/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python2.7/distutils/core.py", line 137, in setup
        ok = dist.parse_command_line()
      File "/tmp/pip-install-zu5MqZ/fancycompleter/.eggs/setupmeta-2.6.18-py2.7.egg/setupmeta/hook.py", line 23, in distutils_hook
        dist._setupmeta = SetupMeta(dist)
      File "/tmp/pip-install-zu5MqZ/fancycompleter/.eggs/setupmeta-2.6.18-py2.7.egg/setupmeta/model.py", line 626, in __init__
        self.pkg_info = PackageInfo(MetaDefs.project_dir)
      File "/tmp/pip-install-zu5MqZ/fancycompleter/.eggs/setupmeta-2.6.18-py2.7.egg/setupmeta/model.py", line 403, in __init__
        lines = load_contents(self.path)
      File "/tmp/pip-install-zu5MqZ/fancycompleter/.eggs/setupmeta-2.6.18-py2.7.egg/setupmeta/content.py", line 29, in load_contents
        for line in fh:
      File "/usr/local/lib/python2.7/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3592: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Reported at: https://github.com/pdbpp/fancycompleter/issues/32

I've converted the README to ascii for now.

**Comment by zsimic** [comment]
Interesting! This is supposed to work, wasn't able to reproduce until I `unset LC_ALL` and `unset LANG`.

Before unsetting, I had:
```
~: env | grep -i utf
LC_ALL=en_US.UTF-8
LANG=en_US.UTF-8
```

setupmeta calls `io.open(full_path, "rt")`, which I thought was enough to handle unicode, and it is apparently, but provided that default encoding can be determined from env vars?

This happens also only in py2.7 indeed.

Is there a way to make this not depend on env vars?

**Comment by zsimic** [comment]
Closing this as I think there's not much that can be done.
If we find a way to make py2.7 not require `LC_ALL` or `LANG` defined, we can contribute that to the code at that time.
