### ISSUE TITLE
2.7.11 doesn't "build"

### ISSUE THREAD

**Issue by marillat** [zsimic/setupmeta#55]
I'm packaging setupmeta since 2.6.3 but the "build" fail with the latest release.

Build is Debian unstable with python 3.8.4RC1

PR #54 is probably the guilty.
````
I: pybuild base:217: /usr/bin/python3 setup.py build 
--- Bootstrapping first pass

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2458, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: module 'setupmeta.hook' has no attribute 'register'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 69, in <module>
    setuptools.setup(**args)
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 143, in setup
    _install_setup_requires(attrs)
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 131, in _install_setup_requires
    dist = distutils.core.Distribution(dict(
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 425, in __init__
    _Distribution.__init__(self, {
  File "/usr/lib/python3.8/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 717, in finalize_options
    ep(self)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 724, in _finalize_setup_keywords
    ep.load()(self, ep.name, value)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2460, in resolve
    raise ImportError(str(exc))
ImportError: module 'setupmeta.hook' has no attribute 'register'

E: pybuild pybuild:352: build: plugin distutils failed with: exit code=1: /usr/bin/python3 setup.py build 
dh_auto_build: error: pybuild --build -i python{version} -p 3.8 returned exit code 13
````

**Comment by zsimic** [comment]
The hook was renamed indeed, this would happen only if you're somehow using the old setupmeta instead of the new.

Can you clean your build artifacts, especially this: `rm -rf .eggs/` -> does the error still occur after you do that?

**Comment by marillat** [comment]
.eggs doesn't exist.

When I do a build for a new version, I unpack the latest release tarball and then i unpack a debian directory.

**Comment by marillat** [comment]
I found what is wrong. The setup.py code read installed python files. Here we have setupmeta 2.7.0 installed and thus the build fail.
After I removed the setupmeta package installed I can build and rebuild this version.

**Comment by zsimic** [comment]
Is the change acceptable then?
Changes like this (renamed functions) can be disruptive indeed, but sometimes they point out things you may not have realized (like an older version being somehow used).

Overall, would you say this was in the end a helpful change or was it just disruptive for no good reason?

**Comment by marillat** [comment]
The best is to dicuss this issue with @matthewwardrop 

Seems to be reasonable when I read in pr #54 
```
We also use this as an opportunity to verify that setupmeta is
initialized correctly, just in case `setup_requires` is populated late
(which appears to be the case in some contexts).
```

**Comment by zsimic** [comment]
Yup, I pinged @matthewwardrop as well earlier (should have done mention here actually, didn't think of that).

After finding the issue, would you say it was worth then?
Seems like you found IIUC a place where setupmeta 2.7.0 (older version) was somehow used in your setup?

**Comment by matthewwardrop** [comment]
Thanks for pinging me @zsimic (and sorry for my tardiness, the last couple of days have been gruelling!).

@marillat Apologies for the hassle! I changed the name for internal clarity, but I can reproduce your issue. The first time you run setup.py if you have a different version installed, you get the error. On subsequent attempts things work fine. I put a raise in the installed version's source code just to see why it is being imported, and here's the stack trace:
```
Traceback (most recent call last):
  File "setup.py", line 37, in <module>
    packages=find_packages(exclude=('tests*',)),
  File "/home/mawardrop/Repositories/netflix/xp-env/conda/lib/python3.7/site-packages/setuptools/__init__.py", line 164, in setup
    _install_setup_requires(attrs)
  File "/home/mawardrop/Repositories/netflix/xp-env/conda/lib/python3.7/site-packages/setuptools/__init__.py", line 159, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/home/mawardrop/Repositories/netflix/xp-env/conda/lib/python3.7/site-packages/setuptools/dist.py", line 702, in fetch_build_eggs
    replace_conflicting=True,
  File "/home/mawardrop/Repositories/netflix/xp-env/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/home/mawardrop/Repositories/netflix/xp-env/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/home/mawardrop/Repositories/netflix/xp-env/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/home/mawardrop/Repositories/netflix/xp-env/conda/lib/python3.7/site-packages/setuptools/dist.py", line 758, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "/home/mawardrop/Repositories/netflix/xp-env/conda/lib/python3.7/site-packages/setuptools/installer.py", line 133, in fetch_build_egg
    wheel.install_as_egg(dist_location)
  File "/home/mawardrop/Repositories/netflix/xp-env/conda/lib/python3.7/site-packages/setuptools/wheel.py", line 99, in install_as_egg
    self._install_as_egg(destination_eggdir, zf)
  File "/home/mawardrop/Repositories/netflix/xp-env/conda/lib/python3.7/site-packages/setuptools/wheel.py", line 107, in _install_as_egg
    self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
  File "/home/mawardrop/Repositories/netflix/xp-env/conda/lib/python3.7/site-packages/setuptools/wheel.py", line 160, in _convert_metadata
    extras_require=extras_require,
  File "/home/mawardrop/Repositories/netflix/xp-env/conda/lib/python3.7/site-packages/setuptools/dist.py", line 430, in __init__
    k: v for k, v in attrs.items()
  File "/home/mawardrop/Repositories/netflix/xp-env/conda/lib/python3.7/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/home/mawardrop/Repositories/netflix/xp-env/conda/lib/python3.7/site-packages/setuptools/dist.py", line 721, in finalize_options
    ep(self)
  File "/home/mawardrop/Repositories/netflix/xp-env/conda/lib/python3.7/site-packages/setuptools/dist.py", line 728, in _finalize_setup_keywords
    ep.load()(self, ep.name, value)
  File "/home/mawardrop/Repositories/netflix/xp-env/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/home/mawardrop/Repositories/netflix/xp-env/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/mawardrop/Repositories/netflix/xp-env/conda/lib/python3.7/site-packages/setupmeta/__init__.py", line 9, in <module>
    raise RuntimeError("HOW DARE YOU!")
RuntimeError: HOW DARE YOU!
```

I'm not sure why pkg_resources needs to import the package when it already knows that the version is not going to satisfy the constraints in my setup.py, but... it does. Given that it will be easier to work around this behaviour that upstream a patch, I think it is sensible to add an alias to `register_keyword` to support the old entrypoint. Removing the new entrypoint would cause the same problem to people in the short-term.

I have to imagine that there aren't many installations of setupmeta though, since it serves no purpose except during setup initialisation... so I'll let @zsimic make the call here.
